# =========================================
# STORAGE CLASS Y PERSISTENT VOLUMES
# Para Redis de Falcosidekick
# =========================================


---
# StorageClass para local storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
# PersistentVolume en worker 1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-worker01
  labels:
    type: local
    app: redis
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker01  # ⚠️ CAMBIAR por tu nombre de nodo

---
# PersistentVolume en worker 2
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-worker02
  labels:
    type: local
    app: redis
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker02  # ⚠️ CAMBIAR por tu nombre de nodo
